baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'letsflutter.in'
theme = 'congo'
enableEmoji = true
summaryLength = 0

[taxonomies]
  tag = "tags"

[params.homepage]
  layout = "custom"
  showRecent = true
  mainSections = ["blog"]

[[menu.main]]
  name = "Blogs"
  pageRef = "blog"
  weight = 40

  [[menu.main]]
  name = "GitHub"
  url = "https://github.com/leo-elstin/"
  weight = 40